name: Тестирование Coveralls

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Установка Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Сделать gradlew исполняемым
        run: chmod +x ./gradlew

      - name: Запуск тестов
        run: ./gradlew test

      - name: Генерация JaCoCo отчетов
        run: ./gradlew jacocoTestReport

      - name: Загрузка Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/reports/jacoco/test/lcov.info

      - name: Публикация HTML-отчета (необязательно)
        uses: actions/upload-artifact@v2
        with:
          name: JaCoCo HTML Coverage Report
          path: ./build/reports/jacoco/test/html
