on: ["push", "pull_request"]

name: Тестирование Coveralls

jobs:

  build:
    name: Сборка
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Использовать Java 17 (замените на нужную версию)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Установить зависимости (отредактируйте для вашего инструмента сборки)
        run: |
          mvn install (или ваша эквивалентная команда)

      - name: Запуск тестов с покрытием (измените имя, если нужно)
        run: |
          mvn test -Dtest=your.test.package (или ваша эквивалентная команда)

      - name: Загрузка Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Замените на ваш токен Coveralls
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

