name: Kotlin CI with Gradle and KSP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build --console=plain

      - name: Run tests
        run: ./gradlew test --console=plain

      - name: Generate Jacoco report
        run: ./gradlew jacocoTestReport --console=plain

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/reports/jacoco/test/jacocoTestReport.xml
