name: CI/CD with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Установить Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew

      - name: Запуск тестов
        run: |
          ./gradlew test

      - name: Загрузка Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
