on: ["push", "pull_request"]

name: Тестирование Coveralls

jobs:

  build:
    name: Сборка
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Использовать Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Установить зависимости
        run: |
          mvn install

      - name: Запуск тестов с покрытием
        run: |
          mvn test -Dtest=your.test.package

      - name: Загрузка Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

