name: Тестирование Coveralls

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Установка Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Сделать gradlew исполняемым
        run: chmod +x ./gradlew

      - name: Запуск тестов и генерация JaCoCo отчетов
        run: |
          ./gradlew test jacocoTestReport jacocoTestCoverageVerification
          mv ./build/reports/jacoco/test/jacocoTestReport.xml ./jacoco.xml

      - name: Отправка отчета на Coveralls
        uses: coverallsapp/github-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-coverage: ./jacoco.xml

