on: ["push", "pull_request"]

name: Тестирование Coveralls

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Установить Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew

      - name: Запуск тестов
        run: |
          ./gradlew test

      - name: Загрузка Coveralls
        uses: coverallsapp/github-action@v2
