on: ["push", "pull_request"]

name: Тестирование Coveralls

jobs:

  build:
    name: Сборка
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Установить Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew

      - name: Установить зависимости
        run: |
          ./gradlew install

      - name: Запуск тестов с покрытием
        run: |
          ./gradlew test --coverage

      - name: Загрузка Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
